"""empty message

Revision ID: 26382752f8c7
Revises: abd376b6dc17
Create Date: 2019-09-27 17:28:57.535975

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '26382752f8c7'
down_revision = 'abd376b6dc17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('name', sa.String(length=100), nullable=True))
    op.drop_index('email', table_name='role')
    op.create_unique_constraint(None, 'role', ['name'])
    op.drop_column('role', 'email')
    op.add_column('user', sa.Column('email', sa.String(length=100), nullable=True))
    op.drop_index('login', table_name='user')
    op.create_unique_constraint(None, 'user', ['email'])
    op.drop_column('user', 'login')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('login', mysql.VARCHAR(length=150), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('login', 'user', ['login'], unique=True)
    op.drop_column('user', 'email')
    op.add_column('role', sa.Column('email', mysql.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'role', type_='unique')
    op.create_index('email', 'role', ['email'], unique=True)
    op.drop_column('role', 'name')
    # ### end Alembic commands ###
