"""empty message

Revision ID: 41ed00738d56
Revises: 
Create Date: 2019-09-11 18:31:18.959172

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '41ed00738d56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=150), nullable=True))
    op.drop_column('user', 'login')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('login', mysql.VARCHAR(length=150), nullable=True))
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
