"""empty message

Revision ID: 9ece5f9d384a
Revises: 26382752f8c7
Create Date: 2019-09-27 21:39:17.213548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ece5f9d384a'
down_revision = '26382752f8c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('book_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'author', 'books', ['book_id'], ['id'])
    op.add_column('books', sa.Column('year', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'year')
    op.drop_constraint(None, 'author', type_='foreignkey')
    op.drop_column('author', 'book_id')
    # ### end Alembic commands ###
