"""empty message

Revision ID: abd376b6dc17
Revises: c7e91600ecf0
Create Date: 2019-09-27 17:25:20.742575

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'abd376b6dc17'
down_revision = 'c7e91600ecf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('email', sa.String(length=100), nullable=True))
    op.drop_index('name', table_name='role')
    op.create_unique_constraint(None, 'role', ['email'])
    op.drop_column('role', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('name', mysql.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'role', type_='unique')
    op.create_index('name', 'role', ['name'], unique=True)
    op.drop_column('role', 'email')
    # ### end Alembic commands ###
