"""empty message

Revision ID: fa2637a787d6
Revises: 9ece5f9d384a
Create Date: 2019-09-27 21:44:40.775055

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa2637a787d6'
down_revision = '9ece5f9d384a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('author_ibfk_1', 'author', type_='foreignkey')
    op.drop_column('author', 'book_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('book_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('author_ibfk_1', 'author', 'books', ['book_id'], ['id'])
    # ### end Alembic commands ###
